#!/usr/bin/env bash

git config --global credential.helper osxkeychain
git config --global user.name adilosa95
git config --global user.email adilosa95@gmail.com

export DOTGIT="$DOTPATH/git"

#Configuramos el gitignore global
mv $DOTGIT/.gitignore $HOME

git config --global core.excludesfile ~/.gitignore

echo '----Git configurado🐙----'