#!/usr/bin/env bash 

#Preferences in Dock
defaults write com.apple.dock workspaces-auto-swoosh -bool NO 

defaults write com.apple.dock autohide -bool true

sudo killall Dock

defaults write -g com.apple.mouse.scaling 5.0

echo "---Preferencias configuradas 🙂"